# Generated by Django 2.2.16 on 2022-03-22 14:02

from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20220317_2119"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ("-year",),
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.RemoveField(
            model_name="title",
            name="rating",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=20, unique=True, verbose_name="Часть URL адреса группы"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название жанра"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                max_length=20, unique=True, verbose_name="Часть URL адреса группы"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.Category",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание произведения"),
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="titles", to="reviews.Genre"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Название произведения"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                help_text="Используйте формат ввода года выпуска: <YYYY>",
                validators=[reviews.validators.year_validator],
                verbose_name="Год",
            ),
        ),
    ]
