# Generated by Django 2.2.16 on 2022-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220327_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
